sonar.projectKey=garridoandreag_banco_ceiba
sonar.organization=garridoandreag

sonar.sources=app,components,constants,lib,types
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,.next/**,coverage/**

sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.jsx,**/*.test.tsx,**/*.spec.js,**/*.spec.ts,**/*.spec.jsx,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
